#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=generate_ds_image
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=06:00:00
#SBATCH --output=slurm_outputs/generate_ds_img_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

# Navigate to the project directory
cd $HOME/vlm_uncertainty/

source activate llava-experiments

export VLM_UQ_STORAGE_ROOT="${VLM_UQ_STORAGE_ROOT:-/projects/prjs2014}"
export VLM_UQ_USER_STORAGE_ROOT="${VLM_UQ_USER_STORAGE_ROOT:-$VLM_UQ_STORAGE_ROOT/$USER}"

export HF_HOME="${HF_HOME:-$VLM_UQ_USER_STORAGE_ROOT/hf_home}"
export HF_DATASETS_CACHE="${HF_DATASETS_CACHE:-$VLM_UQ_USER_STORAGE_ROOT/hf_datasets}"
export TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-$VLM_UQ_USER_STORAGE_ROOT/hf_transformers}"

mkdir -p "$HF_HOME" "$HF_DATASETS_CACHE" "$TRANSFORMERS_CACHE"

export VLM_UQ_PREP_CACHE="${VLM_UQ_PREP_CACHE:-$VLM_UQ_USER_STORAGE_ROOT/vlm_uq_prepared_cache}"
mkdir -p "$VLM_UQ_PREP_CACHE"


#set variables
VLM_ID="llava-hf/llava-1.5-7b-hf"
DATASET="imagenet-r"
OUTPUT_DIR="${OUTPUT_DIR:-$VLM_UQ_STORAGE_ROOT/imagenet_r_16mc}"
SEED=42
DEVICE="cuda"

echo "Saving to: $OUTPUT_DIR"

srun python -u -m src.cli.generate \
    --vlm $VLM_ID \
    --dataset $DATASET \
    --output_dir $OUTPUT_DIR \
    --seed $SEED \
    --device $DEVICE \
    --k_options 16 \
    --clip_negatives \
    --clip_mode gt_to_text \
