#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=qwen_test_fused
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:20:00
#SBATCH --output=slurm_outputs/patching/qwen/test_fused_fix_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

cd "$HOME/vlm_uncertainty/" || exit 1

source activate llava-experiments

export VLM_UQ_STORAGE_ROOT="${VLM_UQ_STORAGE_ROOT:-/projects/prjs2014}"
export VLM_UQ_USER_STORAGE_ROOT="${VLM_UQ_USER_STORAGE_ROOT:-$VLM_UQ_STORAGE_ROOT/$USER}"
export HF_HOME="${HF_HOME:-$VLM_UQ_USER_STORAGE_ROOT/hf_home}"

mkdir -p slurm_outputs/patching/qwen

srun python -u scripts/patching/qwen/test_fused_fix.py
