#!/bin/bash

#SBATCH --partition=gpu_a100
#SBATCH --gpus=1
#SBATCH --job-name=environment
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=00:05:00
#SBATCH --output=slurm_outputs/environment_download_%A.out

module purge
module load 2025
module load Anaconda3/2025.06-1

# Navigate to the project directory
cd $HOME/Thesis/Probe_Experiments

# Create conda environment from environment.yaml
conda env update -f environment.yaml